name: cardinal_android
description: Android implementation of the cardinal plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: cardinal
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: CardinalPlugin
        dartPluginClass: CardinalAndroid

dependencies:
  flutter:
    sdk: flutter
  cardinal_platform_interface:
    path: ../cardinal_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
