name: cardinal
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cardinal_android
      ios:
        default_package: cardinal_ios

dependencies:
  flutter:
    sdk: flutter
  cardinal_android:
    path: ../cardinal_android
  cardinal_ios:
    path: ../cardinal_ios
  cardinal_platform_interface:
    path: ../cardinal_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
